language: go

go:
  - 1.18.x

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'secret'

env:
  - GO111MODULE=on redisPwd=secret  

before_install:
  - go get -v -t ./...

script:
  - go test  -v -race -coverprofile='coverage.out' -covermode=atomic -coverpkg ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)